/*
 * MetaData.java
 * generated by rose
 */

package bn.blaszczyk.rose;


public class MetaData
{
	private int metaData_id = 0;

	private String modelpackage = null;

	private String srcpath = "src/";

	private String sqlpath = "sql/";

	private boolean usingForeignKeys = false;

	private boolean usingAnnotations = false;

	private String database = null;


	public MetaData()
	{
	}

	public MetaData( String modelpackage, String srcpath, String sqlpath, boolean usingForeignKeys, boolean usingAnnotations, String database )
	{
		this.modelpackage = modelpackage;
		this.srcpath = srcpath;
		this.sqlpath = sqlpath;
		this.usingForeignKeys = usingForeignKeys;
		this.usingAnnotations = usingAnnotations;
		this.database = database;
	}

	public int getMetaData_id()
	{
		return metaData_id;
	}

	public void setMetaData_id( int metaData_id )
	{
		this.metaData_id = metaData_id;
	}

	public String getModelpackage()
	{
		return modelpackage;
	}

	public void setModelpackage( String modelpackage )
	{
		this.modelpackage = modelpackage;
	}

	public String getSrcpath()
	{
		return srcpath;
	}

	public void setSrcpath( String srcpath )
	{
		this.srcpath = srcpath;
	}

	public String getSqlpath()
	{
		return sqlpath;
	}

	public void setSqlpath( String sqlpath )
	{
		this.sqlpath = sqlpath;
	}

	public boolean isUsingForeignKeys()
	{
		return usingForeignKeys;
	}

	public void setUsingForeignKeys( boolean usingForeignKeys )
	{
		this.usingForeignKeys = usingForeignKeys;
	}

	public boolean isUsingAnnotations()
	{
		return usingAnnotations;
	}

	public void setUsingAnnotations( boolean usingAnnotations )
	{
		this.usingAnnotations = usingAnnotations;
	}

	public String getDatabase()
	{
		return database;
	}

	public void setDatabase( String database )
	{
		this.database = database;
	}

}
