/*
 * MetaDataParser.java
 * generated by rose
 */

package bn.blaszczyk.rose;


public class MetaDataParser
{
	public static void parseProperty( MetaData metaData, String property, String value )
	{
		switch( property.toLowerCase() )
		{
		case "metadata_id":
			metaData.setMetaData_id( Integer.parseInt( value ) );
			break;
		case "srcpath":
			metaData.setSrcpath( value );
			break;
		case "sqlpath":
			metaData.setSqlpath( value );
			break;
		case "usingforeignkeys":
			metaData.setUsingForeignKeys( Boolean.parseBoolean( value ) );
			break;
		case "database":
			metaData.setDatabase( value );
			break;
		case "modelpackage":
			metaData.setModelpackage( value );
			break;
		case "usingannotations":
			metaData.setUsingAnnotations( Boolean.parseBoolean( value ) );
			break;
		case "controllerpackage":
			metaData.setControllerpackage( value );
			break;
		case "controllerclass":
			metaData.setControllerclass( value );
			break;
		case "entitymodelpackage":
			metaData.setEntitymodelpackage( value );
			break;
		case "entitymodelformat":
			metaData.setEntitymodelformat( value );
			break;
		case "entitymodelfactoryclass":
			metaData.setEntitymodelfactoryclass( value );
			break;
		default:
			System.out.println( "Unknown Property: " + property + " in MetaData");
		}
	}
}
