/*
 * MetaData.java
 * generated by rose
 */
package bn.blaszczyk.rose;


public class MetaData implements bn.blaszczyk.roseapp.model.Entity, Comparable<MetaData>
{

	private int id = -1;
	private String srcpath = "src/";
	private String sqlpath = "sql/";
	private Boolean usingForeignKeys = false;
	private String dbtype = "mysql";
	private String dbuser = "root";
	private String dbpassword = "";
	private String dbserver = "localhost";
	private String dbport = "3306";
	private String dbname = "MyDB";
	private String mainpackage = null;
	private String mainname = "Main";
	private String modelpackage = null;
	private Boolean usingAnnotations = false;
	private String parserpackage = null;
	private String parserformat = "%sParser";


	public MetaData()
	{
	}


	@Override
	public Integer getId()
	{
		return id;
	}

	@Override
	public void setId( Integer id )
	{
		this.id = id;
	}


	public String getSrcpath()
	{
		return srcpath;
	}

	public void setSrcpath( String srcpath )
	{
		this.srcpath = srcpath;
	}


	public String getSqlpath()
	{
		return sqlpath;
	}

	public void setSqlpath( String sqlpath )
	{
		this.sqlpath = sqlpath;
	}


	public Boolean isUsingForeignKeys()
	{
		return usingForeignKeys;
	}

	public void setUsingForeignKeys( Boolean usingForeignKeys )
	{
		this.usingForeignKeys = usingForeignKeys;
	}


	public String getDbtype()
	{
		return dbtype;
	}

	public void setDbtype( String dbtype )
	{
		this.dbtype = dbtype;
	}


	public String getDbuser()
	{
		return dbuser;
	}

	public void setDbuser( String dbuser )
	{
		this.dbuser = dbuser;
	}


	public String getDbpassword()
	{
		return dbpassword;
	}

	public void setDbpassword( String dbpassword )
	{
		this.dbpassword = dbpassword;
	}


	public String getDbserver()
	{
		return dbserver;
	}

	public void setDbserver( String dbserver )
	{
		this.dbserver = dbserver;
	}


	public String getDbport()
	{
		return dbport;
	}

	public void setDbport( String dbport )
	{
		this.dbport = dbport;
	}


	public String getDbname()
	{
		return dbname;
	}

	public void setDbname( String dbname )
	{
		this.dbname = dbname;
	}


	public String getMainpackage()
	{
		return mainpackage;
	}

	public void setMainpackage( String mainpackage )
	{
		this.mainpackage = mainpackage;
	}


	public String getMainname()
	{
		return mainname;
	}

	public void setMainname( String mainname )
	{
		this.mainname = mainname;
	}


	public String getModelpackage()
	{
		return modelpackage;
	}

	public void setModelpackage( String modelpackage )
	{
		this.modelpackage = modelpackage;
	}


	public Boolean isUsingAnnotations()
	{
		return usingAnnotations;
	}

	public void setUsingAnnotations( Boolean usingAnnotations )
	{
		this.usingAnnotations = usingAnnotations;
	}


	public String getParserpackage()
	{
		return parserpackage;
	}

	public void setParserpackage( String parserpackage )
	{
		this.parserpackage = parserpackage;
	}


	public String getParserformat()
	{
		return parserformat;
	}

	public void setParserformat( String parserformat )
	{
		this.parserformat = parserformat;
	}

	@Override
	public int compareTo(MetaData that)
	{
		return Integer.compare( this.id, that.id );
	}

	@Override
	public String toString()
	{
		return "null";
	}

	@Override
	public boolean equals( Object that)
	{
		if(!(that instanceof MetaData))
			return false;
		return this.id == ((MetaData)that).id;
	}

}
