package bn.blaszczyk.rose.creators;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.List;

import bn.blaszczyk.rose.MetaData;
import bn.blaszczyk.rose.model.Entity;
import bn.blaszczyk.rose.model.EntityMember;
import bn.blaszczyk.rose.model.Member;

public class CreateSQL {
	
	public static void createCreateTables(List<Entity> entities, MetaData metadata)
	{
		String fullpath = metadata.getSqlpath() + "createtables.sql";
		File file = new File(fullpath);
		if(!file.getParentFile().exists())
			file.getParentFile().mkdirs();
		try(FileWriter writer = new FileWriter(file))
		{
			writer.write("--createtables.sql\n--generated by rose\n\n");
			for(Entity entity : entities)
				createTable(entity, metadata, writer);
			System.out.println( "File created: " + fullpath);
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
	}
	
	private static void createTable(Entity entity, MetaData metadata, Writer writer) throws IOException
	{
		// create table
		writer.write( "create table " + entity.getSqlname() + "\n(\n" );
		
		// member columns
		for(Member member : entity.getMembers())
		{
			writer.write( "\t" + member.getSqlname() + " " + member.getSqltype());
			if(member.isPrimary())
				writer.write( " auto_increment");
			else if(member.getDefvalue() != null)
				writer.write( " default " + member.getDefvalue() );
			writer.write(",\n");
		}
		
		// relational columns
		for(EntityMember entityMember : entity.getEntityMembers())
			if(!entityMember.isMany())
				writer.write( "\t" + entityMember.getSqlname() + " " 
							+ entityMember.getEntity().getPrimary().getSqltype() + ",\n" );
		
		// primary key
		writer.write( "\tconstraint pk_" + entity.getSqlname().toLowerCase() + " primary key ( " );
		boolean first = true;
		for(Member member : entity.getMembers())
			if(member.isPrimary())
			{
				if(first)
					first = false;
				else
					writer.write(", ");
				writer.write( member.getSqlname() );
			}
		writer.write(" )");
		
		//foreign keys
		if(metadata.isUsingForeignKeys())
			for(EntityMember entityMember : entity.getEntityMembers())
				if(!entityMember.isMany())
					writer.write( ",\n\tconstraint fk_" + entity.getSqlname().toLowerCase() + "_" + entityMember.getEntity().getSqlname().toLowerCase()
								+ " foreign key ( " + entityMember.getSqlname() + " ) references "
								+ entityMember.getEntity().getSqlname() + "( " + entityMember.getEntity().getPrimary().getSqlname() + " )");		
		//fin
		writer.write( "\n);\n\n" );
	}

	public static void createDeleteTables(List<Entity> entities, MetaData metadata)
	{
		String fullpath = metadata.getSqlpath() + "deletetables.sql";
		File file = new File(fullpath);
		if(!file.getParentFile().exists())
			file.getParentFile().mkdirs();
		try(FileWriter writer = new FileWriter(file))
		{
			writer.write("--deletetables.sql\n--generated by rose\n\n");
			for(int i = entities.size() - 1; i >= 0; i-- )
				writer.write("delete table " + entities.get(i).getSqlname() + ";\n");
			System.out.println( "File created: " + fullpath);
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
	}
}


