package bn.blaszczyk.rose.creators;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import bn.blaszczyk.rose.*;
import bn.blaszczyk.rose.model.*;


public class JavaFullPanelCreator {

	public static void create(Entity entity, MetaData metadata)
	{
		String classname = String.format( metadata.getFullpanelformat() , entity.getClassname() );
		String parentclass = metadata.getFullpanelclass().substring(metadata.getFullpanelclass().lastIndexOf(".") + 1);
		String fullpath = metadata.getSrcpath() + metadata.getPanelpackage().replaceAll("\\.", "/") + "/" + classname + ".java";
		File file = new File(fullpath);
		if(!file.getParentFile().exists())
			file.getParentFile().mkdirs();
		try(FileWriter writer = new FileWriter(file))
		{
			// initial comment
			writer.write("/*\n * " + classname + ".java\n * generated by rose\n */\n\n");
			
			// package declaration
			writer.write("package " + metadata.getPanelpackage() + ";\n\n");
			
			// imports
			writer.write("import " + metadata.getModelpackage() + ".*;\n");
			writer.write("import " + metadata.getFullpanelclass() + ";\n");
			writer.write("import javax.swing.*;\n");
			for(String importpackage : entity.getImports())
				if(importpackage != null)
					writer.write("import " + importpackage + ";\n");
			
			// class declaration
			writer.write("\npublic class " + classname + " extends " + parentclass + "\n{\n");
			
			// viewn object
//			writer.write("\tprivate final " + entity.getClassname() + " " + entity.getJavaname() + ";\n");

			// default constructor
			writer.write("\n\n\tpublic " + classname + "( " + entity.getClassname() + " " + entity.getJavaname() + " )\n\t{\n");
//			writer.write("\t\tthis." + entity.getJavaname() + " = " + entity.getJavaname() + ";\n");
			writer.write("\t\taddTitle(\"" + entity.getClassname() + "\");\n" );
			writer.write("\t\taddBasicPanel( new " + String.format( metadata.getBasicpanelformat() , entity.getClassname() ) + "( " 
						 + entity.getJavaname() + " ) );\n");
			for(EntityMember entityMember: entity.getEntityMembers())
				if(entityMember.isMany())
					continue;
				else
				{
					writer.write("\t\taddSubTitle(\"" + entityMember.getCapitalName() + "\");\n" );
					writer.write("\t\taddBasicPanel( new " + String.format( metadata.getBasicpanelformat() , entityMember.getEntity().getClassname() ) + "( " 
								 + entity.getJavaname() + ".get" + entityMember.getCapitalName() + "() ) );\n");
					
				}
			writer.write("\t}\n\n");
			
			// fin
			writer.write("}\n");
			System.out.println( "File created: " + fullpath);
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
		
	}
}
