package bn.blaszczyk.rose.creators;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import bn.blaszczyk.rose.*;
import bn.blaszczyk.rose.model.*;


public class JavaEnumCreator {

	/*
	 * create Enum
	 */
	public static void create(EnumType enumType, MetaData metadata) throws RoseException
	{
		String fullpath = metadata.getSrcpath() + metadata.getModelpackage().replaceAll("\\.", "/") + "/" + enumType.getSimpleClassName() + ".java";
		File file = new File(fullpath);
		if(!file.getParentFile().exists())
			file.getParentFile().mkdirs();
		try(FileWriter writer = new FileWriter(file))
		{
			// initial comment
			writer.write("/*\r\n * " + enumType.getSimpleClassName() + ".java\r\n * generated by rose\r\n */\r\n");
			
			// package declaration
			writer.write("package " + metadata.getModelpackage() + ";\r\n\r\n");
			
			// class declaration
			writer.write("public enum " + enumType.getSimpleClassName() + "\r\n"
					+ "{");
			
			// options variables
			boolean first = true;
			for(String option : enumType)
			{
				if(first)
					first = false;
				else
					writer.write( "," );
				writer.write("\r\n\t" + option  );
			}
			// fin
			writer.write(";\r\n"
					+ "}\r\n");
			System.out.println( "File created: " + fullpath);
		}
		catch (IOException e)
		{
			throw new RoseException("Error creating enum java files", e);
		}
		
	}
	
}
