package bn.blaszczyk.rose.creators;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

import bn.blaszczyk.rose.MetaData;
import bn.blaszczyk.rose.model.Entity;

public class JavaMainCreator {
	
	private static final String CONTROLLER_PACKAGE = "bn.blaszczyk.roseapp.controller.";
	
	public static void create(List<Entity> entities, MetaData metadata)
	{
		String classname = metadata.getMainname();
		String fullpath = metadata.getSrcpath() + metadata.getMainpackage().replaceAll("\\.", "/") + "/" + classname + ".java";
		File file = new File(fullpath);
		if(!file.getParentFile().exists())
			file.getParentFile().mkdirs();
		try(FileWriter writer = new FileWriter(file))
		{		
			// initial comment
			writer.write("/*\n * " + metadata.getMainname() + ".java\n * generated by rose\n */\n\n");
			
			// package declaration
			writer.write("package " + metadata.getMainpackage() + ";\n\n");
			
			// class declaration
			writer.write("\npublic class " + classname + "\n{\n\n");
			
			// main
			writer.write("\tpublic static void main(String[] args)\n\t{\n"
					+ "\t\t" + CONTROLLER_PACKAGE + "BasicModelController basicModelController = new " + metadata.getControllerpackage() + "." + metadata.getControllerclass() + "();\n"
					+ "\t\t" + CONTROLLER_PACKAGE + "FullModelController fullModelController = new " + CONTROLLER_PACKAGE + "HibernateController(basicModelController);\n");
			boolean first = true;
			writer.write("\t\tfullModelController.loadEntities(new Class<?>[]{");
			for(Entity entity : entities)
			{
				if(first)
					first = false;
				else
					writer.write(", ");
				writer.write( entity.getClassName() + ".class");
			}
			writer.write("});\n");
			writer.write("\t\t" + CONTROLLER_PACKAGE + "GUIController guiController = new " + CONTROLLER_PACKAGE + "GUIController(fullModelController);\n");
			writer.write( "\t\tguiController.createMainFrame( new Class<?>[]{");
			first = true;
			for(Entity entity : entities)
			{
				if(first)
					first = false;
				else
					writer.write(", ");
				writer.write( entity.getClassName() + ".class");
			}
			writer.write("}, \"" + metadata.getMainname() + "\" );\n");
			writer.write("\t}\n");
			
			//fin
			writer.write("}\n");
			System.out.println( "File created: " + fullpath);
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
	}
	
}
