package bn.blaszczyk.rose.creators;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import bn.blaszczyk.rose.*;
import bn.blaszczyk.rose.model.*;


public class JavaBasicPanelCreator {

	public static void create(Entity entity, MetaData metadata)
	{
		String classname = String.format( metadata.getSimplepanelformat() , entity.getClassname() );
		String parentclass = metadata.getBasicpanelclass().substring(metadata.getBasicpanelclass().lastIndexOf(".") + 1);
		String fullpath = metadata.getSrcpath() + metadata.getPanelpackage().replaceAll("\\.", "/") + "/" + classname + ".java";
		File file = new File(fullpath);
		if(!file.getParentFile().exists())
			file.getParentFile().mkdirs();
		try(FileWriter writer = new FileWriter(file))
		{
			// initial comment
			writer.write("/*\n * " + classname + ".java\n * generated by rose\n */\n\n");
			
			// package declaration
			writer.write("package " + metadata.getPanelpackage() + ";\n\n");
			
			// imports
			writer.write("import " + metadata.getModelpackage() + ".*;\n");
			writer.write("import " + metadata.getBasicpanelclass() + ";\n");
			writer.write("import javax.swing.*;\n");
			for(String importpackage : entity.getImports())
				if(importpackage != null)
					writer.write("import " + importpackage + ";\n");
			
			// class declaration
			writer.write("\npublic class " + classname + " extends " + parentclass + "\n{\n");
			
			// viewn object
//			writer.write("\tprivate final " + entity.getClassname() + " " + entity.getJavaname() + ";\n");

			// default constructor
			writer.write("\n\n\tpublic " + classname + "( " + entity.getClassname() + " " + entity.getJavaname() + " )\n\t{\n");
//			writer.write("\t\tthis." + entity.getJavaname() + " = " + entity.getJavaname() + ";\n");
			for(Member member : entity.getMembers())
				writer.write( "\t\taddValue( \"" + member.getCapitalName() + "\", " 
							+ entity.getJavaname() + ".get" + member.getCapitalName()+ "().toString() );\n" );
			writer.write("\t}\n\n");
			
			// fin
			writer.write("}\n");
			System.out.println( "File created: " + fullpath);
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
		
	}
}
