package bn.blaszczyk.rose.creators;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import bn.blaszczyk.rose.*;
import bn.blaszczyk.rose.model.*;


public class JavaFullPanelCreator {

	public static void create(Entity entity, MetaData metadata)
	{
		String classname = String.format( metadata.getFullpanelformat() , entity.getClassname() );
		String parentclass = metadata.getFullpanelclass().substring(metadata.getFullpanelclass().lastIndexOf(".") + 1);
		String fullpath = metadata.getSrcpath() + metadata.getPanelpackage().replaceAll("\\.", "/") + "/" + classname + ".java";
		File file = new File(fullpath);
		if(!file.getParentFile().exists())
			file.getParentFile().mkdirs();
		try(FileWriter writer = new FileWriter(file))
		{
			// initial comment
			writer.write("/*\n * " + classname + ".java\n * generated by rose\n */\n\n");
			
			// package declaration
			writer.write("package " + metadata.getPanelpackage() + ";\n\n");
			
			// imports
			writer.write("import " + metadata.getModelpackage() + ".*;\n");
			writer.write("import " + metadata.getFullpanelclass() + ";\n");
			writer.write("import bn.blaszczyk.rose.interfaces.*;\n");
			writer.write("import javax.swing.*;\n");
			for(String importpackage : entity.getImports())
				if(importpackage != null)
					writer.write("import " + importpackage + ";\n");
			
			// class declaration
			writer.write("\npublic class " + classname + " extends " + parentclass + "\n{\n");
			
			// viewn object
//			writer.write("\tprivate final " + entity.getClassname() + " " + entity.getJavaname() + ";\n");

			// default constructor
			writer.write("\n\n\tpublic " + classname + "( " + entity.getClassname() + " " + entity.getJavaname() + ", GUIController controller )\n\t{\n");
			writer.write("\t\tsuper( " + entity.getJavaname() + ", controller );\n");
//			writer.write("\t\tthis." + entity.getJavaname() + " = " + entity.getJavaname() + ";\n");
			writer.write("\t}\n\n");
			
			// implement mehtods

			writer.write("\t@Override\n\tpublic String getName()\n\t{\n\t\treturn \"" + entity.getClassname() + "\";\n\t}\n\n");
			
			writer.write("\t@Override\n\tpublic int getEntityCount()\n\t{\n\t\treturn " + entity.getEntityMembers().size() + ";\n\t}\n\n");

			writer.write("\t@Override\n\tpublic String getEntityName(int index)\n\t{\n\t\tswitch(index)\n\t\t{\n");
			int count = 0;
			for(EntityMember entityMember : entity.getEntityMembers())
				writer.write("\t\tcase " + count++ + ":\n\t\t\treturn \"" + entityMember.getCapitalName() + ( entityMember.isMany() ? "s" : "" ) +  "\";\n" );
			writer.write("\t\t}\n\t\treturn \"\";\n\t}\n\n");

			writer.write("\t@Override\n\tpublic Object getEntityMember(int index)\n\t{\n\t\tswitch(index)\n\t\t{\n");
			count = 0;
			for(EntityMember entityMember : entity.getEntityMembers())
				writer.write("\t\tcase " + count++ + ":\n\t\t\treturn ((" + entity.getClassname() + ")getObject()).get" + entityMember.getCapitalName() 
							+ ( entityMember.isMany() ? "s" : "" ) +  "();\n" );
			writer.write("\t\t}\n\t\treturn null;\n\t}\n\n");
			
			writer.write("\t@Override\n\tpublic boolean isEntityMany(int index)\n\t{\n\t\tswitch(index)\n\t\t{\n");
			count = 0;
			for(EntityMember entityMember : entity.getEntityMembers())
				writer.write("\t\tcase " + count++ + ":\n\t\t\treturn " + entityMember.isMany() + ";\n" );
			writer.write("\t\t}\n\t\treturn false;\n\t}\n\n");

			
			// fin
			writer.write("}\n");
			System.out.println( "File created: " + fullpath);
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
		
	}
}
