package bn.blaszczyk.rose.creators;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

import bn.blaszczyk.rose.MetaData;
import bn.blaszczyk.rose.model.Entity;
import bn.blaszczyk.rose.model.Member;
import bn.blaszczyk.rose.model.MemberType;

public class JavaControllerCreator {
	
	public static void create(List<Entity> entities, MetaData metadata)
	{
		String fullpath = metadata.getSrcpath() + metadata.getControllerpackage().replaceAll("\\.", "/") + "/" + metadata.getControllerclass() + ".java";
		File file = new File(fullpath);
		if(!file.getParentFile().exists())
			file.getParentFile().mkdirs();
		try(FileWriter writer = new FileWriter(file))
		{
			// initial comment
			writer.write("/*\n * " + metadata.getControllerclass() + ".java\n * generated by rose\n */\n\n");
			
			// package declaration
			writer.write("package " + metadata.getControllerpackage() + ";\n\n");
			
			// imports
			writer.write("import " + metadata.getModelpackage() + ".*;\n"
						+ "import " + metadata.getPanelpackage() + ".*;\n"
						+ "import bn.blaszczyk.rose.interfaces.*;" );
			
			// class declaration
			writer.write("\npublic class " + metadata.getControllerclass() + " implements GUIController\n{\n");

			// createBasicPanel
			writer.write("\n\t@Override\n\tpublic BasicPanel createBasicPanel( Object object )\n\t{\n\t\t");
			for(Entity entity : entities)
				writer.write("if( object instanceof " + entity.getClassname() +" )\n\t\t\treturn new " 
							+ String.format( metadata.getBasicpanelformat(), entity.getClassname() ) +  "( ( " + entity.getClassname() + " ) object );\n\t\telse " );
			writer.write("\n\t\t\treturn null;\n\t}\n" );

			// createFullPanel
			writer.write("\n\t@Override\n\tpublic FullPanel createFullPanel( Object object )\n\t{\n\t\t");
			for(Entity entity : entities)
				writer.write("if( object instanceof " + entity.getClassname() +" )\n\t\t\treturn new " 
							+ String.format( metadata.getFullpanelformat(), entity.getClassname() ) +  "( ( " + entity.getClassname() + " ) object, this );\n\t\telse " );
			writer.write("\n\t\t\treturn null;\n\t}\n" );
			
			writer.write("}\n");
			System.out.println( "File created: " + fullpath);
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
		
	}
	
	
}
